# Task Planning ROS Action

# Goal definition
bool reset
stacking_ros/RobotConfig robot_config
BodyInfo[] blocks
GoalInfo[] goal
---
# Result definition
bool success
TaskAction[] plan
---
# Feedback
bool processing